### ISSUE TITLE
Buy order and minus funds

### ISSUE THREAD

**Issue by 0xwhalerush** [BuildOnViction/bug-reports#7]
My balance is only 60 TOMO, I try order buy 59 tomo. why buy order is 59 tomo 2x . I only ordered 1x because the max buy was 59 tomo and  funds to minus
![IMG_20191220_125123](https://user-images.githubusercontent.com/59077947/71233747-13245180-2329-11ea-8e5b-5916a24afc40.jpg)
![IMG_20191220_125057](https://user-images.githubusercontent.com/59077947/71233748-14557e80-2329-11ea-9b7c-433dc2d903b9.jpg)

Tomo addres : 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

**Comment by thanhson1085** [comment]
We can not reproduce your issue with Chrome on desktop.
You have to show the device, OS, browser and steps you did to create the issue.

**Comment by 0xwhalerush** [comment]
On android
Device Type / Model: Mobile Phone / CPH1729 
Operating System: Android version 7.1.1 (32-bit) 
Browser: Chrome version 76.0.3809.89 (32-bit)

**Comment by 0xwhalerush** [comment]
steps you did to create the issue.
1.the beginning of my balance is only 60 tomo and max buy 59 tomo on dex
2. I tried to buy 59 tomo , with 1 time of purchase why buy orders occur 2x of purchase 
3.balance becomes minus

**Comment by thanhson1085** [comment]
TomoDEX will not support mobile browser, only support DApp on TomoWallet (mobile)
Which linux distro?
What address did you use for the test?

**Comment by 0xwhalerush** [comment]
Same issue i use tomowallet

**Comment by WhaleCMD** [comment]
Mobile

**Comment by 0xwhalerush** [comment]
My addres test

https://scan.testnet.tomochain.com/address/0x681da2D4c56F4A8D872975d7f1f702F4e100D1cE

**Comment by 0xwhalerush** [comment]
update !!! the order history becomes reject

![IMG_20191220_145529](https://user-images.githubusercontent.com/59077947/71239349-ebd58080-2338-11ea-9a98-87307d3e4da0.jpg)

**Comment by thanhson1085** [comment]
Yep, We will check on our tomowallet dapp, this is just a display issue.
If you create 2 order, and your balance is not enough for the order, it will be reject. So you can see 1 filled, 1 rejected.

**Comment by 0xwhalerush** [comment]
is this not a bug?

**Comment by thanhson1085** [comment]
Not sure, please wait, we need CPH1729 device model to reproduce your issue. The issue doesn't appear on our device.

**Comment by 0xwhalerush** [comment]
Okay

**Comment by 0xwhalerush** [comment]
please tell the next news

**Comment by 0xwhalerush** [comment]
> Not sure, please wait, we need CPH1729 device model to reproduce your issue. The issue doesn't appear on our device.

It is my android

**Comment by 0xwhalerush** [comment]
will this get a prize?

**Comment by thanhson1085** [comment]
We can not reproduce the issue on our device. You have to wait util the team can reproduce the issue to get a prize.
You can help team by share videos that show us the steps to reproduce the issue.

**Comment by 0xwhalerush** [comment]
How long do you think?
 I have written everything above

> We can not reproduce the issue on our device. You have to wait util the team can reproduce the issue to get a prize.
> You can help team by share videos that show us the steps to reproduce the issue.

How long do you think?
Step by step issue  I have written everything above

**Comment by chinhnt23** [comment]
@WhaleCMD I highly suggest you can assist the team by reproducing the issue and send us here as we can't due to device model differences

**Comment by 0xwhalerush** [comment]
My issue
1.the beginning of my balance is only 60 tomo and max buy 59 tomo on dex
2. I tried to buy 59 tomo 
3. I click 2x orders very quickly, so it becomes like that, it should not be able to order 2x because of lack of balance

**Comment by 0xwhalerush** [comment]
2-5x klik buy order very fast

**Comment by 0xwhalerush** [comment]
You can try it on other devices, bro

**Comment by thanhson1085** [comment]
Thank you for the details. We will try it again.

**Comment by 0xwhalerush** [comment]
Okay broo

**Comment by WhaleCMD** [comment]
No reward ?

**Comment by 0xwhalerush** [comment]
> Thank you for the details. We will try it again.

please tell the next news

**Comment by 0xwhalerush** [comment]
> @WhaleCMD I highly suggest you can assist the team by reproducing the issue and send us here as we can't due to device model differences

 How ? Next news broo

**Comment by thanhson1085** [comment]
> 3. I click 2x orders very quickly, so it becomes like that, it should not be able to order 2x because of lack of balance

Not easy, but we reproduced the issue, It is a display issue. Thank you
![Image from iOS](https://user-images.githubusercontent.com/546540/71959028-538a3780-3224-11ea-8269-3d6ff52568b3.png)

@chinhnt23

**Comment by chinhnt23** [comment]
Thank you @WhaleCMD , I will process the bounty soon

**Comment by 0xwhalerush** [comment]
Okay thanks

**Comment by 0xwhalerush** [comment]
How many tomo I can from this bug

**Comment by 0xwhalerush** [comment]
Bug resolve?

**Comment by thanhson1085** [comment]
Not yet, we will try to fix it.

<img width="610" alt="Annotation 2020-03-01 094035" src="https://user-images.githubusercontent.com/546540/75618422-d387aa80-5ba0-11ea-97c2-f163a8c55cc1.png">

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5
Thx regards

**Comment by 0xwhalerush** [comment]
![IMG_20200304_171324](https://user-images.githubusercontent.com/59077947/75868983-7ce9cd00-5e3b-11ea-90be-7e53d4830d35.jpg)
I see bug resolved

**Comment by thanhson1085** [comment]
I still reproduced the issue. We are trying to fix it.

**Comment by 0xwhalerush** [comment]
I have tried this issue, my suggestion has been solved :)

**Comment by WhaleCMD** [comment]
@chinhnt23 resolved?

**Comment by WhaleCMD** [comment]
Hi @thanhson1085 i try bug resolved

**Comment by WhaleCMD** [comment]
@victorngn  it is resolved no reward?

**Comment by thanhson1085** [comment]
The team confirmed that It has NOT resolved yet. 
Do not try to spam the program, you will be banned.

**Comment by 0xwhalerush** [comment]
![Screenshot_2020-04-08-12-30-58-95](https://user-images.githubusercontent.com/59077947/78747924-ddb57980-7994-11ea-80e0-e9fae4e87bb1.png)
Excuse me @thanhson1085 @chinhnt23 it is resolved?

**Comment by 0xwhalerush** [comment]
maybe you forgot to confirm resolved, I ask thanks :)

**Comment by thanhson1085** [comment]
Resolved @chinhnt23

**Comment by WhaleCMD** [comment]
Tomo ad

**Comment by 0xwhalerush** [comment]
Tomo addres 0xE5922e8E8536A88c18e38C29f4cd7C032CdEAEB5

Thx

**Comment by chinhnt23** [comment]
I will proceed to bounty tomorrow @WhaleCMD @thanhson1085

**Comment by 0xwhalerush** [comment]
No today?

**Comment by chinhnt23** [comment]
@WhaleCMD I have sent the Bounty, pls confirm

**Comment by 0xwhalerush** [comment]
Thx received
